// This file is part of Adlib Tracker II (AT2).
//
// SPDX-FileType: SOURCE
// SPDX-FileCopyrightText: 2014-2024 The Adlib Tracker 2 Authors
// SPDX-License-Identifier: GPL-3.0-or-later

const AT2ExtKeyCode EASCIIKeymap[0x100] = {
  /*0x00*/ ATEK_UNKNOWN,
  /*0x01*/ MK_EKEY (ATK_ESCAPE)       | ATEK_MOD_ALT,
  /*0x02*/ MK_EKEY (ATK_1)            | ATEK_MOD_CTRL,
  /*0x03*/ MK_EKEY (ATK_2)            | ATEK_MOD_CTRL,
  /*0x04*/ MK_EKEY (ATK_3)            | ATEK_MOD_CTRL,
  /*0x05*/ MK_EKEY (ATK_4)            | ATEK_MOD_CTRL,
  /*0x06*/ MK_EKEY (ATK_5)            | ATEK_MOD_CTRL,
  /*0x07*/ MK_EKEY (ATK_6)            | ATEK_MOD_CTRL,
  /*0x08*/ MK_EKEY (ATK_7)            | ATEK_MOD_CTRL,
  /*0x09*/ MK_EKEY (ATK_8)            | ATEK_MOD_CTRL,
  /*0x0A*/ MK_EKEY (ATK_9)            | ATEK_MOD_CTRL,
  /*0x0B*/ MK_EKEY (ATK_0)            | ATEK_MOD_CTRL,
  /*0x0C*/ MK_EKEY (ATK_MINUS)        | ATEK_MOD_CTRL,
  /*0x0D*/ MK_EKEY (ATK_EQUALS)       | ATEK_MOD_CTRL,
  /*0x0E*/ MK_EKEY (ATK_BACKSPACE)    | ATEK_MOD_ALT,
  /*0x0F*/ MK_EKEY (ATK_TAB)          | ATEK_MOD_SHIFT,
  /*0x10*/ MK_EKEY (ATK_q)            | ATEK_MOD_ALT,
  /*0x11*/ MK_EKEY (ATK_w)            | ATEK_MOD_ALT,
  /*0x12*/ MK_EKEY (ATK_e)            | ATEK_MOD_ALT,
  /*0x13*/ MK_EKEY (ATK_r)            | ATEK_MOD_ALT,
  /*0x14*/ MK_EKEY (ATK_t)            | ATEK_MOD_ALT,
  /*0x15*/ MK_EKEY (ATK_y)            | ATEK_MOD_ALT,
  /*0x16*/ MK_EKEY (ATK_u)            | ATEK_MOD_ALT,
  /*0x17*/ MK_EKEY (ATK_i)            | ATEK_MOD_ALT,
  /*0x18*/ MK_EKEY (ATK_o)            | ATEK_MOD_ALT,
  /*0x19*/ MK_EKEY (ATK_p)            | ATEK_MOD_ALT,
  /*0x1A*/ MK_EKEY (ATK_LEFTBRACKET)  | ATEK_MOD_ALT,
  /*0x1B*/ MK_EKEY (ATK_RIGHTBRACKET) | ATEK_MOD_ALT,
  /*0x1C*/ MK_EKEY (ATK_ENTER)        | ATEK_MOD_ALT,
  /*0x1D*/ ATEK_UNKNOWN,              // Left or Right Control
  /*0x1E*/ MK_EKEY (ATK_a)            | ATEK_MOD_ALT,
  /*0x1F*/ MK_EKEY (ATK_s)            | ATEK_MOD_ALT,
  /*0x20*/ MK_EKEY (ATK_d)            | ATEK_MOD_ALT,
  /*0x21*/ MK_EKEY (ATK_f)            | ATEK_MOD_ALT,
  /*0x22*/ MK_EKEY (ATK_g)            | ATEK_MOD_ALT,
  /*0x23*/ MK_EKEY (ATK_h)            | ATEK_MOD_ALT,
  /*0x24*/ MK_EKEY (ATK_j)            | ATEK_MOD_ALT,
  /*0x25*/ MK_EKEY (ATK_k)            | ATEK_MOD_ALT,
  /*0x26*/ MK_EKEY (ATK_l)            | ATEK_MOD_ALT,
  /*0x27*/ MK_EKEY (ATK_SEMICOLON)    | ATEK_MOD_ALT,
  /*0x28*/ MK_EKEY (ATK_QUOTE)        | ATEK_MOD_ALT,
  /*0x29*/ MK_EKEY (ATK_BACKQUOTE)    | ATEK_MOD_ALT,
  /*0x2A*/ ATEK_UNKNOWN,              // Left Shift
  /*0x2B*/ MK_EKEY (ATK_BACKSLASH)    | ATEK_MOD_ALT,
  /*0x2C*/ MK_EKEY (ATK_z)            | ATEK_MOD_ALT,
  /*0x2D*/ MK_EKEY (ATK_x)            | ATEK_MOD_ALT,
  /*0x2E*/ MK_EKEY (ATK_c)            | ATEK_MOD_ALT,
  /*0x2F*/ MK_EKEY (ATK_v)            | ATEK_MOD_ALT,
  /*0x30*/ MK_EKEY (ATK_b)            | ATEK_MOD_ALT,
  /*0x31*/ MK_EKEY (ATK_n)            | ATEK_MOD_ALT,
  /*0x32*/ MK_EKEY (ATK_m)            | ATEK_MOD_ALT,
  /*0x33*/ MK_EKEY (ATK_COMMA)        | ATEK_MOD_ALT,
  /*0x34*/ MK_EKEY (ATK_PERIOD)       | ATEK_MOD_ALT,
  /*0x35*/ MK_EKEY (ATK_SLASH)        | ATEK_MOD_ALT,
  /*0x36*/ ATEK_UNKNOWN,              // Right Shift
  /*0x37*/ MK_EKEY (ATK_KP_MULTIPLY)  | ATEK_MOD_ALT,
  /*0x38*/ ATEK_UNKNOWN,              // Left or Right Alt
  /*0x39*/ ATEK_UNKNOWN,              // Space
  /*0x3A*/ ATEK_UNKNOWN,              // Caps Lock
  /*0x3B*/ MK_EKEY (ATK_F1),
  /*0x3C*/ MK_EKEY (ATK_F2),
  /*0x3D*/ MK_EKEY (ATK_F3),
  /*0x3E*/ MK_EKEY (ATK_F4),
  /*0x3F*/ MK_EKEY (ATK_F5),
  /*0x40*/ MK_EKEY (ATK_F6),
  /*0x41*/ MK_EKEY (ATK_F7),
  /*0x42*/ MK_EKEY (ATK_F8),
  /*0x43*/ MK_EKEY (ATK_F9),
  /*0x44*/ MK_EKEY (ATK_F10),
  /*0x45*/ ATEK_UNKNOWN,              // Num Lock
  /*0x46*/ ATEK_UNKNOWN,              // Scroll Lock
  /*0x47*/ MK_EKEY (ATK_HOME),        // Keypad 7
  /*0x48*/ MK_EKEY (ATK_UP),          // Keypad 8
  /*0x49*/ MK_EKEY (ATK_PAGEUP),      // Keypad 9
  /*0x4A*/ MK_EKEY (ATK_KP_MINUS)     | ATEK_MOD_ALT, // Keypad -
  /*0x4B*/ MK_EKEY (ATK_LEFT),        // Keypad 4
  /*0x4C*/ ATEK_UNKNOWN,              // Keypad 5
  /*0x4D*/ MK_EKEY (ATK_RIGHT),       // Keypad 6
  /*0x4E*/ MK_EKEY (ATK_KP_PLUS)      | ATEK_MOD_ALT, // Keypad +
  /*0x4F*/ MK_EKEY (ATK_END),         // Keypad 1
  /*0x50*/ MK_EKEY (ATK_DOWN),        // Keypad 2
  /*0x51*/ MK_EKEY (ATK_PAGEDOWN),    // Keypad 3
  /*0x52*/ MK_EKEY (ATK_INSERT),      // Keypad 0
  /*0x53*/ MK_EKEY (ATK_DELETE),      // Keypad .
  /*0x54*/ MK_EKEY (ATK_F1)           | ATEK_MOD_SHIFT,
  /*0x55*/ MK_EKEY (ATK_F2)           | ATEK_MOD_SHIFT,
  /*0x56*/ MK_EKEY (ATK_F3)           | ATEK_MOD_SHIFT,
  /*0x57*/ MK_EKEY (ATK_F4)           | ATEK_MOD_SHIFT,
  /*0x58*/ MK_EKEY (ATK_F5)           | ATEK_MOD_SHIFT,
  /*0x59*/ MK_EKEY (ATK_F6)           | ATEK_MOD_SHIFT,
  /*0x5A*/ MK_EKEY (ATK_F7)           | ATEK_MOD_SHIFT,
  /*0x5B*/ MK_EKEY (ATK_F8)           | ATEK_MOD_SHIFT,
  /*0x5C*/ MK_EKEY (ATK_F9)           | ATEK_MOD_SHIFT,
  /*0x5D*/ MK_EKEY (ATK_F10)          | ATEK_MOD_SHIFT,
  /*0x5E*/ MK_EKEY (ATK_F1)           | ATEK_MOD_CTRL,
  /*0x5F*/ MK_EKEY (ATK_F2)           | ATEK_MOD_CTRL,
  /*0x60*/ MK_EKEY (ATK_F3)           | ATEK_MOD_CTRL,
  /*0x61*/ MK_EKEY (ATK_F4)           | ATEK_MOD_CTRL,
  /*0x62*/ MK_EKEY (ATK_F5)           | ATEK_MOD_CTRL,
  /*0x63*/ MK_EKEY (ATK_F6)           | ATEK_MOD_CTRL,
  /*0x64*/ MK_EKEY (ATK_F7)           | ATEK_MOD_CTRL,
  /*0x65*/ MK_EKEY (ATK_F8)           | ATEK_MOD_CTRL,
  /*0x66*/ MK_EKEY (ATK_F9)           | ATEK_MOD_CTRL,
  /*0x67*/ MK_EKEY (ATK_F10)          | ATEK_MOD_CTRL,
  /*0x68*/ MK_EKEY (ATK_F1)           | ATEK_MOD_ALT,
  /*0x69*/ MK_EKEY (ATK_F2)           | ATEK_MOD_ALT,
  /*0x6A*/ MK_EKEY (ATK_F3)           | ATEK_MOD_ALT,
  /*0x6B*/ MK_EKEY (ATK_F4)           | ATEK_MOD_ALT,
  /*0x6C*/ MK_EKEY (ATK_F5)           | ATEK_MOD_ALT,
  /*0x6D*/ MK_EKEY (ATK_F6)           | ATEK_MOD_ALT,
  /*0x6E*/ MK_EKEY (ATK_F7)           | ATEK_MOD_ALT,
  /*0x6F*/ MK_EKEY (ATK_F8)           | ATEK_MOD_ALT,
  /*0x70*/ MK_EKEY (ATK_F9)           | ATEK_MOD_ALT,
  /*0x71*/ MK_EKEY (ATK_F10)          | ATEK_MOD_ALT,
  /*0x72*/ MK_EKEY (ATK_PRTSCR),
  /*0x73*/ MK_EKEY (ATK_LEFT)         | ATEK_MOD_CTRL,
  /*0x74*/ MK_EKEY (ATK_RIGHT)        | ATEK_MOD_CTRL,
  /*0x75*/ MK_EKEY (ATK_END)          | ATEK_MOD_CTRL,
  /*0x76*/ MK_EKEY (ATK_PAGEDOWN)     | ATEK_MOD_CTRL,
  /*0x77*/ MK_EKEY (ATK_HOME)         | ATEK_MOD_CTRL,
  /*0x78*/ MK_EKEY (ATK_1)            | ATEK_MOD_ALT,
  /*0x79*/ MK_EKEY (ATK_2)            | ATEK_MOD_ALT,
  /*0x7A*/ MK_EKEY (ATK_3)            | ATEK_MOD_ALT,
  /*0x7B*/ MK_EKEY (ATK_4)            | ATEK_MOD_ALT,
  /*0x7C*/ MK_EKEY (ATK_5)            | ATEK_MOD_ALT,
  /*0x7D*/ MK_EKEY (ATK_6)            | ATEK_MOD_ALT,
  /*0x7E*/ MK_EKEY (ATK_7)            | ATEK_MOD_ALT,
  /*0x7F*/ MK_EKEY (ATK_8)            | ATEK_MOD_ALT,
  /*0x80*/ MK_EKEY (ATK_9)            | ATEK_MOD_ALT,
  /*0x81*/ MK_EKEY (ATK_0)            | ATEK_MOD_ALT,
  /*0x82*/ MK_EKEY (ATK_MINUS)        | ATEK_MOD_ALT,
  /*0x83*/ MK_EKEY (ATK_EQUALS)       | ATEK_MOD_ALT,
  /*0x84*/ MK_EKEY (ATK_PAGEUP)       | ATEK_MOD_CTRL,
  /*0x85*/ MK_EKEY (ATK_F11),
  /*0x86*/ MK_EKEY (ATK_F12),
  /*0x87*/ MK_EKEY (ATK_F11)          | ATEK_MOD_SHIFT,
  /*0x88*/ MK_EKEY (ATK_F12)          | ATEK_MOD_SHIFT,
  /*0x89*/ MK_EKEY (ATK_F11)          | ATEK_MOD_CTRL,
  /*0x8A*/ MK_EKEY (ATK_F12)          | ATEK_MOD_CTRL,
  /*0x8B*/ MK_EKEY (ATK_F11)          | ATEK_MOD_ALT,
  /*0x8C*/ MK_EKEY (ATK_F12)          | ATEK_MOD_ALT,
  /*0x8D*/ MK_EKEY (ATK_KP_8)         | ATEK_MOD_CTRL,
  /*0x8E*/ MK_EKEY (ATK_KP_MINUS)     | ATEK_MOD_CTRL,
  /*0x8F*/ MK_EKEY (ATK_KP_5)         | ATEK_MOD_CTRL,
  /*0x90*/ MK_EKEY (ATK_KP_PLUS)      | ATEK_MOD_CTRL,
  /*0x91*/ MK_EKEY (ATK_KP_2)         | ATEK_MOD_CTRL,
  /*0x92*/ MK_EKEY (ATK_KP_0)         | ATEK_MOD_CTRL,
  /*0x93*/ MK_EKEY (ATK_KP_PERIOD)    | ATEK_MOD_CTRL,
  /*0x94*/ MK_EKEY (ATK_TAB)          | ATEK_MOD_CTRL,
  /*0x95*/ MK_EKEY (ATK_KP_DIVIDE)    | ATEK_MOD_CTRL,
  /*0x96*/ MK_EKEY (ATK_KP_MULTIPLY)  | ATEK_MOD_CTRL,
  /*0x97*/ MK_EKEY (ATK_HOME)         | ATEK_MOD_ALT,
  /*0x98*/ MK_EKEY (ATK_UP)           | ATEK_MOD_ALT,
  /*0x99*/ MK_EKEY (ATK_PAGEUP)       | ATEK_MOD_ALT,
  /*0x9A*/ ATEK_UNKNOWN,              // ?
  /*0x9B*/ MK_EKEY (ATK_LEFT)         | ATEK_MOD_ALT,
  /*0x9C*/ ATEK_UNKNOWN,              // ?
  /*0x9D*/ MK_EKEY (ATK_RIGHT)        | ATEK_MOD_ALT,
  /*0x9E*/ ATEK_UNKNOWN,              // ?
  /*0x9F*/ MK_EKEY (ATK_END)          | ATEK_MOD_ALT,
  /*0xA0*/ MK_EKEY (ATK_DOWN)         | ATEK_MOD_ALT,
  /*0xA1*/ MK_EKEY (ATK_PAGEDOWN)     | ATEK_MOD_ALT,
  /*0xA2*/ MK_EKEY (ATK_INSERT)       | ATEK_MOD_ALT,
  /*0xA3*/ MK_EKEY (ATK_DELETE)       | ATEK_MOD_ALT,
  /*0xA4*/ MK_EKEY (ATK_KP_DIVIDE)    | ATEK_MOD_ALT,
  /*0xA5*/ MK_EKEY (ATK_TAB)          | ATEK_MOD_ALT,
  /*0xA6*/ MK_EKEY (ATK_KP_ENTER)     | ATEK_MOD_ALT,
  /*0xA7*/ ATEK_UNKNOWN,
  /*0xA8*/ ATEK_UNKNOWN,
  /*0xA9*/ ATEK_UNKNOWN,
  /*0xAA*/ ATEK_UNKNOWN,
  /*0xAB*/ ATEK_UNKNOWN,
  /*0xAC*/ ATEK_UNKNOWN,
  /*0xAD*/ ATEK_UNKNOWN,
  /*0xAE*/ ATEK_UNKNOWN,
  /*0xAF*/ ATEK_UNKNOWN,
  /*0xB0*/ ATEK_UNKNOWN,
  /*0xB1*/ ATEK_UNKNOWN,
  /*0xB2*/ ATEK_UNKNOWN,
  /*0xB3*/ ATEK_UNKNOWN,
  /*0xB4*/ ATEK_UNKNOWN,
  /*0xB5*/ ATEK_UNKNOWN,
  /*0xB6*/ ATEK_UNKNOWN,
  /*0xB7*/ ATEK_UNKNOWN,
  /*0xB8*/ ATEK_UNKNOWN,
  /*0xB9*/ ATEK_UNKNOWN,
  /*0xBA*/ ATEK_UNKNOWN,
  /*0xBB*/ ATEK_UNKNOWN,
  /*0xBC*/ ATEK_UNKNOWN,
  /*0xBD*/ ATEK_UNKNOWN,
  /*0xBE*/ ATEK_UNKNOWN,
  /*0xBF*/ ATEK_UNKNOWN,
  /*0xC0*/ ATEK_UNKNOWN,
  /*0xC1*/ ATEK_UNKNOWN,
  /*0xC2*/ ATEK_UNKNOWN,
  /*0xC3*/ ATEK_UNKNOWN,
  /*0xC4*/ ATEK_UNKNOWN,
  /*0xC5*/ ATEK_UNKNOWN,
  /*0xC6*/ ATEK_UNKNOWN,
  /*0xC7*/ ATEK_UNKNOWN,
  /*0xC8*/ ATEK_UNKNOWN,
  /*0xC9*/ ATEK_UNKNOWN,
  /*0xCA*/ ATEK_UNKNOWN,
  /*0xCB*/ ATEK_UNKNOWN,
  /*0xCC*/ ATEK_UNKNOWN,
  /*0xCD*/ ATEK_UNKNOWN,
  /*0xCE*/ ATEK_UNKNOWN,
  /*0xCF*/ ATEK_UNKNOWN,
  /*0xD0*/ ATEK_UNKNOWN,
  /*0xD1*/ ATEK_UNKNOWN,
  /*0xD2*/ ATEK_UNKNOWN,
  /*0xD3*/ ATEK_UNKNOWN,
  /*0xD4*/ ATEK_UNKNOWN,
  /*0xD5*/ ATEK_UNKNOWN,
  /*0xD6*/ ATEK_UNKNOWN,
  /*0xD7*/ ATEK_UNKNOWN,
  /*0xD8*/ ATEK_UNKNOWN,
  /*0xD9*/ ATEK_UNKNOWN,
  /*0xDA*/ ATEK_UNKNOWN,
  /*0xDB*/ ATEK_UNKNOWN,
  /*0xDC*/ ATEK_UNKNOWN,
  /*0xDD*/ ATEK_UNKNOWN,
  /*0xDE*/ ATEK_UNKNOWN,
  /*0xDF*/ ATEK_UNKNOWN,
  /*0xE0*/ ATEK_UNKNOWN,
  /*0xE1*/ ATEK_UNKNOWN,
  /*0xE2*/ ATEK_UNKNOWN,
  /*0xE3*/ ATEK_UNKNOWN,
  /*0xE4*/ ATEK_UNKNOWN,
  /*0xE5*/ ATEK_UNKNOWN,
  /*0xE6*/ ATEK_UNKNOWN,
  /*0xE7*/ ATEK_UNKNOWN,
  /*0xE8*/ ATEK_UNKNOWN,
  /*0xE9*/ ATEK_UNKNOWN,
  /*0xEA*/ ATEK_UNKNOWN,
  /*0xEB*/ ATEK_UNKNOWN,
  /*0xEC*/ ATEK_UNKNOWN,
  /*0xED*/ ATEK_UNKNOWN,
  /*0xEE*/ ATEK_UNKNOWN,
  /*0xEF*/ ATEK_UNKNOWN,
  /*0xF0*/ ATEK_UNKNOWN,
  /*0xF1*/ ATEK_UNKNOWN,
  /*0xF2*/ ATEK_UNKNOWN,
  /*0xF3*/ ATEK_UNKNOWN,
  /*0xF4*/ ATEK_UNKNOWN,
  /*0xF5*/ ATEK_UNKNOWN,
  /*0xF6*/ ATEK_UNKNOWN,
  /*0xF7*/ ATEK_UNKNOWN,
  /*0xF8*/ ATEK_UNKNOWN,
  /*0xF9*/ ATEK_UNKNOWN,
  /*0xFA*/ ATEK_UNKNOWN,
  /*0xFB*/ ATEK_UNKNOWN,
  /*0xFC*/ ATEK_UNKNOWN,
  /*0xFD*/ ATEK_UNKNOWN,
  /*0xFE*/ ATEK_UNKNOWN,
  /*0xFF*/ ATEK_UNKNOWN
};
