Usage:
  make [option ...] [TARGET]
where:
  option:
    DEBUG=<Boolean>
      <Boolean>: 0 | 1
    BUILD=<BUILD>
      <BUILD>:
        go32v2-i386
    AT2PLAY_VERSION=<VERSION>
      <VERSION>: string without spaces
  TARGET:
    all
    | build-deps | clean-deps
    | build-sdk
    | build-at2play-bin | clean-at2play-bin
    | clean | distclean

Following environment variables may be used:
  GCC
  GCCFLAGS
  GCCFLAGS_DIRS
  FPC
  FPCFLAGS
  FPCFLAGS_DIRS
